from __future__ import annotations

from dataclasses import dataclass
from typing import Callable, Dict, Iterable, List, Tuple

from .geometry import geometry
from .model import HEIGHT, WIDTH, Diagram, Edge, Vertex, bundle_offsets


@dataclass(frozen=True)
class LatexFormat:
    value: str
    label: str
    description: str
    compiler: str


FORMATS = (
    LatexFormat("tikz-feynman", "TikZ-Feynman", "Exact fixed positions, curves, colors, labels, and markers.", "pdfLaTeX, LuaLaTeX, or XeLaTeX."),
    LatexFormat("tikz-feynhand", "TikZ-FeynHand", "Manual TikZ geometry with the FeynHand package.", "pdfLaTeX, LuaLaTeX, or XeLaTeX."),
    LatexFormat("feynmp", "feynMP", "MetaPost output with fixed vertices and native particle styles.", "LaTeX with MetaPost."),
    LatexFormat("feynmf", "feynMF", "METAFONT output with fixed vertices and native particle styles.", "LaTeX with METAFONT."),
    LatexFormat("pst-feyn", "PST-Feyn", "PSTricks output with exact sampled curves.", "LaTeX → dvips → ps2pdf, or pdfLaTeX with auto-pst-pdf."),
    LatexFormat("axodraw2", "axodraw2", "Direct coordinates with exact sampled curves.", "LaTeX, or pdfLaTeX with axohelp."),
)


def _n(value: float) -> str:
    result = str(round(value, 1))
    return "0" if result == "-0.0" else result.rstrip("0").rstrip(".") if "." in result else result


def _rgb(color: str) -> Tuple[float, float, float]:
    return tuple(int(color[index : index + 2], 16) / 255 for index in (1, 3, 5))  # type: ignore[return-value]


def _colors(document: Diagram) -> Dict[str, str]:
    values = ["#172333".upper()] + [edge.color.upper() for edge in document.edges]
    unique = list(dict.fromkeys(values))
    return {value: "fdscolor{}".format(index) for index, value in enumerate(unique)}


def _tikz(document: Diagram, package: str) -> str:
    scale = document.style.widthMm / WIDTH
    colors = _colors(document)
    lines = [
        "% Generated by Feynman Diagram Studio",
        "%% Requires \\usepackage{%s}, \\usepackage{xcolor}, and \\usetikzlibrary{arrows.meta,patterns,decorations.markings}" % package,
    ]
    lines.extend("\\definecolor{%s}{HTML}{%s}" % (name, color[1:]) for color, name in colors.items())
    lines.extend([
        "\\begin{tikzpicture}[x=%.6fmm,y=-%.6fmm]" % (scale, scale),
    ])
    vertices = {item.id: item for item in document.vertices}
    for edge in document.edges:
        start, end = vertices.get(edge.from_), vertices.get(edge.to)
        if start is None or end is None:
            continue
        edge_color = colors[edge.color.upper()]
        options = ["draw=%s" % edge_color, "line width=%spt" % _n(document.style.strokePt), "line cap=round", "line join=round"]
        if edge.kind == "scalar":
            options.append("dash pattern=on 9pt off 7pt")
        elif edge.kind == "ghost":
            options.append("dash pattern=on 1pt off 7pt")
        if edge.arrow == "forward":
            options.extend(("postaction={decorate}", "decoration={markings,mark=at position .5 with {\\arrow{>}}}"))
        elif edge.arrow == "reverse":
            options.extend(("postaction={decorate}", "decoration={markings,mark=at position .5 with {\\arrow{<}}}"))
        for offset in bundle_offsets(edge):
            points, _ = geometry(start, end, edge, offset)
            # The sampled path makes the graphical export agree with the editor for every line type.
            sampled = points[:: max(1, len(points) // 90)]
            if sampled[-1] != points[-1]:
                sampled.append(points[-1])
            coords = " ".join("(%s,%s)" % (_n(x), _n(y)) for x, y in sampled)
            lines.append("  \\draw[%s] plot coordinates {%s};" % (", ".join(options), coords))
        if edge.label:
            _, middle = geometry(start, end, edge)
            x = middle.x + middle.nx * edge.labelOffset
            y = middle.y + middle.ny * edge.labelOffset
            lines.append("  \\node[text=%s] at (%s,%s) {$%s$};" % (edge_color, _n(x), _n(y), edge.label))
    for vertex in document.vertices:
        marker = vertex.marker if vertex.marker else ("dot" if vertex.visible else "none")
        if marker == "dot":
            lines.append("  \\fill[draw=fdscolor0] (%s,%s) circle[radius=2pt];" % (_n(vertex.x), _n(vertex.y)))
        elif marker != "none":
            options = ["draw=fdscolor0", "line width=%spt" % _n(document.style.strokePt)]
            if marker == "filled":
                options.append("fill=fdscolor0")
            elif marker == "hatched":
                options.append("pattern=north east lines")
            elif marker == "crosshatched":
                options.append("pattern=crosshatch")
            elif marker == "dotted":
                options.append("pattern=dots")
            else:
                options.append("fill=white")
            lines.append("  \\path[%s] (%s,%s) circle[radius=%smm];" % (", ".join(options), _n(vertex.x), _n(vertex.y), _n(vertex.markerSize * scale)))
        if vertex.label:
            lines.append("  \\node at (%s,%s) {$%s$};" % (_n(vertex.x + vertex.labelX), _n(vertex.y + vertex.labelY), vertex.label))
    lines.append("\\end{tikzpicture}")
    return "\n".join(lines)


def _fmf(document: Diagram, package: str) -> str:
    graph = "fmfgraph*" if package == "feynmp" else "fmfgraph"
    lines = [
        "% Generated by Feynman Diagram Studio",
        "%% Requires \\usepackage{%s}" % package,
        "\\begin{fmffile}{feynman-diagram}",
        "\\begin{%s}(%s,%s)" % (graph, _n(WIDTH), _n(HEIGHT)),
    ]
    for vertex in document.vertices:
        lines.append("  \\fmfvertex{%s}" % vertex.id)
        lines.append("  \\fmfforce{(%sw,%sh)}{%s}" % (_n(vertex.x / WIDTH), _n(1 - vertex.y / HEIGHT), vertex.id))
        if vertex.label:
            lines.append("  \\fmflabel{$%s$}{%s}" % (vertex.label, vertex.id))
        marker = vertex.marker if vertex.marker else ("dot" if vertex.visible else "none")
        if marker != "none":
            shape = "full" if marker in ("dot", "filled") else "empty"
            size = 4 if marker == "dot" else vertex.markerSize * 2
            lines.append("  \\fmfv{decor.shape=circle,decor.filled=%s,decor.size=%s}{%s}" % (shape, _n(size), vertex.id))
    styles = {"fermion": "fermion", "photon": "photon", "gluon": "gluon", "scalar": "dashes", "ghost": "dots"}
    for edge in document.edges:
        options = [styles[edge.kind]]
        if edge.label:
            options.append("label=$%s$" % edge.label)
        if edge.arrow == "reverse":
            options.append("reverse=true")
        if edge.from_ == edge.to:
            options.extend(("left=1", "tension=0"))
        elif edge.curvature:
            options.append(("left" if edge.curvature > 0 else "right") + "=%s" % _n(min(1.0, abs(edge.curvature) / 180)))
        if package == "feynmp":
            r, g, b = _rgb(edge.color)
            options.append("foreground=(%.3f,%.3f,%.3f)" % (r, g, b))
        for _ in bundle_offsets(edge):
            lines.append("  \\fmf{%s}{%s,%s}" % (", ".join(options), edge.from_, edge.to))
    lines.extend(("\\end{%s}" % graph, "\\end{fmffile}"))
    return "\n".join(lines)


def _pst(document: Diagram) -> str:
    colors = _colors(document)
    lines = [
        "% Generated by Feynman Diagram Studio",
        "% Requires \\usepackage{pst-feyn}, \\usepackage{pstricks-add}, and \\usepackage{xcolor}",
        "% For direct PDF output, load auto-pst-pdf and enable shell escape.",
        "\\begin{pspicture}(0,0)(720,480)",
    ]
    lines[3:3] = ["\\definecolor{%s}{HTML}{%s}" % (name, color[1:]) for color, name in colors.items()]
    vertices = {item.id: item for item in document.vertices}
    for edge in document.edges:
        start, end = vertices.get(edge.from_), vertices.get(edge.to)
        if start is None or end is None:
            continue
        for offset in bundle_offsets(edge):
            points, _ = geometry(start, end, edge, offset)
            sampled = points[:: max(1, len(points) // 80)]
            if sampled[-1] != points[-1]:
                sampled.append(points[-1])
            coords = "".join("(%s,%s)" % (_n(x), _n(HEIGHT - y)) for x, y in sampled)
            style = "linestyle=dashed" if edge.kind in ("scalar", "ghost") else ""
            arrows = "->" if edge.arrow == "forward" else "<-" if edge.arrow == "reverse" else "-"
            lines.append("  \\psline[linecolor=%s,linewidth=%spt,%s]{%s}%s" % (colors[edge.color.upper()], _n(document.style.strokePt), style, arrows, coords))
        if edge.label:
            _, middle = geometry(start, end, edge)
            lines.append("  \\rput(%s,%s){\\color{%s}$%s$}" % (_n(middle.x + middle.nx * edge.labelOffset), _n(HEIGHT - middle.y - middle.ny * edge.labelOffset), colors[edge.color.upper()], edge.label))
    for vertex in document.vertices:
        marker = vertex.marker if vertex.marker else ("dot" if vertex.visible else "none")
        if marker != "none":
            radius = 2 if marker == "dot" else vertex.markerSize
            fill = "fillstyle=solid,fillcolor=fdscolor0" if marker in ("dot", "filled") else "fillstyle=solid,fillcolor=white"
            lines.append("  \\pscircle[%s](%s,%s){%s}" % (fill, _n(vertex.x), _n(HEIGHT - vertex.y), _n(radius)))
        if vertex.label:
            lines.append("  \\rput(%s,%s){$%s$}" % (_n(vertex.x + vertex.labelX), _n(HEIGHT - vertex.y - vertex.labelY), vertex.label))
    lines.append("\\end{pspicture}")
    return "\n".join(lines)


def _axo(document: Diagram) -> str:
    scale = document.style.widthMm * 72.27 / (25.4 * WIDTH)
    lines = [
        "% Generated by Feynman Diagram Studio",
        "% Requires \\usepackage{axodraw2} and \\usepackage{xcolor} (run axohelp for direct PDF).",
        "\\begingroup",
        "\\SetScale{%.5f}" % scale,
        "\\begin{axopicture}(720,480)",
    ]
    vertices = {item.id: item for item in document.vertices}
    for edge in document.edges:
        start, end = vertices.get(edge.from_), vertices.get(edge.to)
        if start is None or end is None:
            continue
        for offset in bundle_offsets(edge):
            points, middle = geometry(start, end, edge, offset)
            sampled = points[:: max(1, len(points) // 100)]
            if sampled[-1] != points[-1]:
                sampled.append(points[-1])
            for a, b in zip(sampled, sampled[1:]):
                command = "DashLine" if edge.kind in ("scalar", "ghost") else "Line"
                suffix = "{5}" if command == "DashLine" else ""
                lines.append("  {\\color[HTML]{%s}\\%s(%s,%s)(%s,%s)%s}" % (edge.color[1:], command, _n(a[0]), _n(HEIGHT - a[1]), _n(b[0]), _n(HEIGHT - b[1]), suffix))
            if edge.arrow != "none":
                angle = math_degrees(middle.tx, -middle.ty) + (180 if edge.arrow == "reverse" else 0)
                lines.append("  {\\color[HTML]{%s}\\Arrow(%s,%s)(%s)}" % (edge.color[1:], _n(middle.x), _n(HEIGHT - middle.y), _n(angle)))
        if edge.label:
            _, middle = geometry(start, end, edge)
            lines.append("  {\\color[HTML]{%s}\\Text(%s,%s)[c]{$%s$}}" % (edge.color[1:], _n(middle.x + middle.nx * edge.labelOffset), _n(HEIGHT - middle.y - middle.ny * edge.labelOffset), edge.label))
    for vertex in document.vertices:
        marker = vertex.marker if vertex.marker else ("dot" if vertex.visible else "none")
        if marker != "none":
            radius = 2 if marker == "dot" else vertex.markerSize
            if marker in ("dot", "filled"):
                lines.append("  \\Vertex(%s,%s){%s}" % (_n(vertex.x), _n(HEIGHT - vertex.y), _n(radius)))
            else:
                lines.append("  \\ECirc(%s,%s)(%s,%s){0}" % (_n(vertex.x), _n(HEIGHT - vertex.y), _n(radius), _n(radius)))
        if vertex.label:
            lines.append("  \\Text(%s,%s)[c]{$%s$}" % (_n(vertex.x + vertex.labelX), _n(HEIGHT - vertex.y - vertex.labelY), vertex.label))
    lines.extend(("\\end{axopicture}", "\\endgroup"))
    return "\n".join(lines)


def math_degrees(x: float, y: float) -> float:
    import math

    return math.degrees(math.atan2(y, x))


def latex_source(document: Diagram, format_name: str) -> str:
    if format_name == "tikz-feynman":
        return _tikz(document, "tikz-feynman")
    if format_name == "tikz-feynhand":
        return _tikz(document, "tikz-feynhand")
    if format_name in ("feynmp", "feynmf"):
        return _fmf(document, format_name)
    if format_name == "pst-feyn":
        return _pst(document)
    if format_name == "axodraw2":
        return _axo(document)
    raise ValueError("Unsupported LaTeX format: {}".format(format_name))


def standalone_source(document: Diagram, format_name: str) -> str:
    option = next((item for item in FORMATS if item.value == format_name), None)
    if option is None:
        raise ValueError("Unsupported LaTeX format: {}".format(format_name))
    packages: Dict[str, Iterable[str]] = {
        "tikz-feynman": (r"\usepackage[compat=1.1.0]{tikz-feynman}", r"\usetikzlibrary{arrows.meta,patterns,decorations.markings}"),
        "tikz-feynhand": (r"\usepackage{tikz-feynhand}", r"\usetikzlibrary{arrows.meta,patterns,decorations.markings}"),
        "feynmp": (r"\usepackage{feynmp}",),
        "feynmf": (r"\usepackage{feynmf}",),
        "pst-feyn": (r"\usepackage{auto-pst-pdf}", r"\usepackage{pst-feyn}", r"\usepackage{pstricks-add}"),
        "axodraw2": (r"\usepackage{axodraw2}",),
    }
    preamble = [r"\documentclass{article}", "% Compiler: " + option.compiler, r"\usepackage{xcolor}"]
    preamble.extend(packages[format_name])
    preamble.extend((r"\pagestyle{empty}", r"\begin{document}", r"\centering", latex_source(document, format_name), r"\end{document}"))
    return "\n".join(preamble)
