from __future__ import annotations

import math
from dataclasses import dataclass
from typing import Callable, Dict, Iterable, List, Tuple

from .geometry import connected_geometry, edge_label_position, geometry, momentum_geometry
from .model import HEIGHT, WIDTH, Diagram, Edge, Vertex, FreeLabel, bundle_offsets


@dataclass(frozen=True)
class LatexFormat:
    value: str
    label: str
    description: str
    compiler: str


FORMATS = (
    LatexFormat("tikz-feynman", "TikZ-Feynman", "Exact fixed positions, curves, colors, labels, and markers.", "pdfLaTeX, LuaLaTeX, or XeLaTeX."),
    LatexFormat("tikz-feynhand", "TikZ-FeynHand", "Manual TikZ geometry with the FeynHand package.", "pdfLaTeX, LuaLaTeX, or XeLaTeX."),
    LatexFormat("feynmp", "feynMP", "MetaPost output with fixed vertices and native particle styles.", "LaTeX with MetaPost."),
    LatexFormat("feynmf", "feynMF", "METAFONT output with fixed vertices and native particle styles.", "LaTeX with METAFONT."),
    LatexFormat("pst-feyn", "PST-Feyn", "PSTricks output with exact sampled curves.", "LaTeX → dvips → ps2pdf, or pdfLaTeX with auto-pst-pdf."),
    LatexFormat("axodraw2", "axodraw2", "Direct coordinates with exact sampled curves.", "LaTeX, or pdfLaTeX with axohelp."),
)


def _n(value: float) -> str:
    result = str(round(value, 1))
    return "0" if result == "-0.0" else result.rstrip("0").rstrip(".") if "." in result else result


def _rgb(color: str) -> Tuple[float, float, float]:
    return tuple(int(color[index : index + 2], 16) / 255 for index in (1, 3, 5))  # type: ignore[return-value]


def _colors(document: Diagram) -> Dict[str, str]:
    values = ["#172333".upper()] + [edge.color.upper() for edge in document.edges]
    values += [edge.momentum.color.upper() for edge in document.edges if edge.momentum]
    values += [item.color.upper() for item in document.annotations]
    unique = list(dict.fromkeys(values))
    return {value: "fdscolor{}".format(index) for index, value in enumerate(unique)}


def _font_command(document: Diagram) -> str:
    return "\\fontsize{%spt}{%spt}\\selectfont" % (_n(document.style.fontPt), _n(document.style.fontPt * 1.2))


def unsupported_features(document: Diagram, format_name: str) -> List[str]:
    if format_name not in (option.value for option in FORMATS):
        return ["Unknown LaTeX format"]
    reasons = []
    if format_name in ("feynmp", "feynmf") and any(edge.bundle > 1 for edge in document.edges):
        reasons.append("Quark bundle spacing is not preserved")
    if format_name == "feynmf" and (any(edge.color.upper() != "#172333" or (edge.momentum and edge.momentum.color.upper() != "#172333") for edge in document.edges) or any(item.color.upper() != "#172333" for item in document.annotations)):
        reasons.append("Custom colors are not supported by feynMF")
    return reasons


def _tikz(document: Diagram, package: str) -> str:
    scale = document.style.widthMm / WIDTH
    colors = _colors(document)
    lines = [
        "% Generated by Feynman Diagram Studio",
        "%% Requires \\usepackage{%s}, \\usepackage{xcolor}, and \\usetikzlibrary{arrows.meta,patterns,decorations.markings}" % package,
        "\\begingroup",
        _font_command(document),
    ]
    lines.extend("\\definecolor{%s}{HTML}{%s}" % (name, color[1:]) for color, name in colors.items())
    lines.extend([
        "\\begin{tikzpicture}[x=%.6fmm,y=-%.6fmm]" % (scale, scale),
    ])
    vertices = {item.id: item for item in document.vertices}
    for edge in document.edges:
        start, end = vertices.get(edge.from_), vertices.get(edge.to)
        if start is None or end is None:
            continue
        edge_color = colors[edge.color.upper()]
        options = ["draw=%s" % edge_color, "line width=%spt" % _n(document.style.strokePt), "line cap=round", "line join=round"]
        if edge.kind == "scalar":
            options.append("dash pattern=on 9pt off 7pt")
        elif edge.kind == "ghost":
            options.append("dash pattern=on 1pt off 7pt")
        if edge.arrow == "forward":
            options.extend(("postaction={decorate}", "decoration={markings,mark=at position .5 with {\\arrow{>}}}"))
        elif edge.arrow == "reverse":
            options.extend(("postaction={decorate}", "decoration={markings,mark=at position .5 with {\\arrow{<}}}"))
        for offset in bundle_offsets(edge):
            points, _ = connected_geometry(document, edge, offset)
            # The sampled path makes the graphical export agree with the editor for every line type.
            sampled = points[:: max(1, len(points) // 90)]
            if sampled[-1] != points[-1]:
                sampled.append(points[-1])
            coords = " ".join("(%s,%s)" % (_n(x), _n(y)) for x, y in sampled)
            lines.append("  \\draw[%s] plot coordinates {%s};" % (", ".join(options), coords))
        if edge.label:
            _, middle = geometry(start, end, edge)
            x, y = edge_label_position(middle, edge)
            lines.append("  \\node[text=%s] at (%s,%s) {$%s$};" % (edge_color, _n(x), _n(y), edge.label))
        if edge.momentum:
            points, arrow, label = momentum_geometry(start, end, edge)
            ink = colors[edge.momentum.color.upper()]
            sampled = points[::max(1, len(points) // 90)]
            if sampled[-1] != points[-1]:
                sampled.append(points[-1])
            coords = " ".join("(%s,%s)" % (_n(x), _n(y)) for x, y in sampled)
            lines.append("  \\draw[draw=%s,line width=%spt] plot coordinates {%s};" % (ink, _n(document.style.strokePt * 0.8), coords))
            lines.append("  \\fill[%s] %s -- cycle;" % (ink, " -- ".join("(%s,%s)" % (_n(x), _n(y)) for x, y in arrow)))
            if edge.momentum.label:
                lines.append("  \\node[text=%s] at (%s,%s) {$%s$};" % (ink, _n(label[0]), _n(label[1]), edge.momentum.label))
    for item in document.annotations:
        ink = colors[item.color.upper()]
        if isinstance(item, FreeLabel):
            if item.text:
                lines.append("  \\node[text=%s] at (%s,%s) {$%s$};" % (ink, _n(item.x), _n(item.y), item.text))
        else:
            lines.append("  \\draw[draw=%s,line width=%spt,-{Stealth[length=3mm]}] (%s,%s) -- (%s,%s);" % (ink, _n(document.style.strokePt), _n(item.x1), _n(item.y1), _n(item.x2), _n(item.y2)))
    for vertex in document.vertices:
        marker = vertex.marker if vertex.marker else ("dot" if vertex.visible else "none")
        if marker == "dot":
            lines.append("  \\fill[draw=fdscolor0] (%s,%s) circle[radius=2pt];" % (_n(vertex.x), _n(vertex.y)))
        elif marker != "none":
            options = ["draw=fdscolor0", "line width=%spt" % _n(document.style.strokePt)]
            if marker == "filled":
                options.append("fill=fdscolor0")
            elif marker == "hatched":
                options.append("pattern=north east lines")
            elif marker == "crosshatched":
                options.append("pattern=crosshatch")
            elif marker == "dotted":
                options.append("pattern=dots")
            else:
                options.append("fill=white")
            lines.append("  \\path[%s] (%s,%s) circle[radius=%smm];" % (", ".join(options), _n(vertex.x), _n(vertex.y), _n(vertex.markerSize * scale)))
        if vertex.label:
            lines.append("  \\node at (%s,%s) {$%s$};" % (_n(vertex.x + vertex.labelX), _n(vertex.y + vertex.labelY), vertex.label))
    lines.append("\\end{tikzpicture}")
    lines.append("\\endgroup")
    return "\n".join(lines)


def _fmf(document: Diagram, package: str) -> str:
    graph = "fmfgraph*"
    vertex_names = {vertex.id: "fdsv{}".format(index) for index, vertex in enumerate(document.vertices)}
    def label_text(source: str) -> str:
        return source.replace(",", r"\mathpunct{\char44}")
    width_pt = document.style.widthMm * 72.27 / 25.4
    exact_positions = bool(document.annotations or any(edge.momentum for edge in document.edges))
    lines = [
        "% Generated by Feynman Diagram Studio",
        "%% Requires \\usepackage{%s}" % package,
        "\\begingroup",
        _font_command(document),
        "\\begin{fmffile}{feynman-diagram}",
        "\\begin{%s}(%s,%s)" % (graph, _n(width_pt), _n(width_pt * HEIGHT / WIDTH)),
        "  \\fmfpen{%spt}" % _n(document.style.strokePt),
    ]
    for vertex in document.vertices:
        x = "%.6f" % (vertex.x / WIDTH) if exact_positions else _n(vertex.x / WIDTH)
        y = "%.6f" % (1 - vertex.y / HEIGHT) if exact_positions else _n(1 - vertex.y / HEIGHT)
        lines.append("  \\fmfforce{(%sw,%sh)}{%s}" % (x, y, vertex_names[vertex.id]))
        marker = vertex.marker if vertex.marker else ("dot" if vertex.visible else "none")
        if marker != "none":
            filling = {"dot": "full", "filled": "full", "open": "empty",
                       "hatched": "shaded", "crosshatched": "hatched", "dotted": "gray10"}[marker]
            # Bare sizes are interpreted differently by MetaPost and METAFONT.
            diameter_pt = 4 if marker == "dot" else 2 * vertex.markerSize * width_pt / WIDTH
            lines.append("  \\fmfv{decor.shape=circle,decor.filled=%s,decor.size=%spt}{%s}" % (filling, _n(diameter_pt), vertex_names[vertex.id]))
    styles = {"fermion": ("plain", "fermion"), "photon": ("photon", "photon"),
              "gluon": ("gluon", "gluon"), "scalar": ("dashes", "scalar"), "ghost": ("dots", "ghost")}
    for edge in document.edges:
        if edge.momentum:
            continue  # Draw annotated paths explicitly after the graph layout is frozen.
        native_arrow = edge.kind in ("fermion", "scalar", "ghost")
        options = [styles[edge.kind][int(native_arrow and edge.arrow != "none")]]
        reverse = native_arrow and edge.arrow == "reverse"
        if edge.from_ == edge.to:
            options.extend(("left=1", "tension=0.5"))
        elif edge.circular or edge.curvature:
            side = edge.curvature > 0
            options.append(("left" if side != reverse else "right") + "=%s" % _n(1 if edge.circular else min(1.0, abs(edge.curvature) / 180)))
        if package == "feynmp":
            r, g, b = _rgb(edge.color)
            options.append("foreground=(%.3f*red+%.3f*green+%.3f*blue)" % (r, g, b))
        for _ in bundle_offsets(edge):
            lines.append("  \\fmf{%s}{%s,%s}" % (", ".join(options), vertex_names[edge.to if reverse else edge.from_], vertex_names[edge.from_ if reverse else edge.to]))
    if any(edge.label or edge.momentum or (edge.arrow != "none" and edge.kind in ("photon", "gluon")) for edge in document.edges) or any(vertex.label for vertex in document.vertices) or document.annotations:
        lines.append("  \\fmffreeze")
    def coordinate(point):
        return "(%.6fw,%.6fh)" % (point[0] / WIDTH, 1 - point[1] / HEIGHT)
    def foreground(color):
        r, g, b = _rgb(color)
        return ",foreground=(%.3f*red+%.3f*green+%.3f*blue)" % (r, g, b) if package == "feynmp" else ""
    for edge in document.edges:
        if edge.momentum:
            start, end = document.vertex(edge.from_), document.vertex(edge.to)
            points, _ = geometry(start, end, edge)
            sampled = points[::max(1, len(points) // 80)]
            if sampled[-1] != points[-1]:
                sampled.append(points[-1])
            style = {"scalar": "dashes", "ghost": "dots"}.get(edge.kind, "plain")
            lines.append("  \\fmfi{%s%s}{%s}" % (style, foreground(edge.color), "--".join(coordinate(point) for point in sampled)))
    for edge in document.edges:
        if edge.arrow != "none" and (edge.momentum or edge.kind in ("photon", "gluon")):
            start, end = document.vertex(edge.from_), document.vertex(edge.to)
            if start and end:
                _, middle = geometry(start, end, edge)
                direction = 1 if edge.arrow == "forward" else -1
                dx, dy = middle.tx * 12 * direction, middle.ty * 12 * direction
                options = "phantom_arrow"
                if package == "feynmp":
                    r, g, b = _rgb(edge.color)
                    options += ",foreground=(%.3f*red+%.3f*green+%.3f*blue)" % (r, g, b)
                lines.append("  \\fmfi{%s}{(%.6fw,%.6fh)--(%.6fw,%.6fh)}" % (options,
                    (middle.x - dx) / WIDTH, 1 - (middle.y - dy) / HEIGHT,
                    (middle.x + dx) / WIDTH, 1 - (middle.y + dy) / HEIGHT))
    for edge in document.edges:
        start, end = document.vertex(edge.from_), document.vertex(edge.to)
        if edge.label and start and end:
            _, middle = geometry(start, end, edge)
            x, y = edge_label_position(middle, edge)
            lines.append("  \\fmfiv{l={$%s$},l.a=0,l.d=0}{(%.6fw,%.6fh)}" % (label_text(edge.label), x / WIDTH, 1 - y / HEIGHT))
    for edge in document.edges:
        if not edge.momentum:
            continue
        start, end = document.vertex(edge.from_), document.vertex(edge.to)
        points, arrow, label = momentum_geometry(start, end, edge)
        sampled = points[::max(1, len(points) // 80)]
        if sampled[-1] != points[-1]:
            sampled.append(points[-1])
        ink = foreground(edge.momentum.color)
        lines.append("  \\fmfi{plain%s}{%s}" % (ink, "--".join(coordinate(point) for point in sampled)))
        tip = arrow[0]
        base = ((arrow[1][0] + arrow[2][0]) / 2, (arrow[1][1] + arrow[2][1]) / 2)
        lines.append("  \\fmfi{phantom_arrow%s}{%s--%s}" % (ink, coordinate(base), coordinate(tip)))
        if edge.momentum.label:
            lines.append("  \\fmfiv{l={\\color[HTML]{%s}$%s$},l.a=0,l.d=0}{%s}" % (edge.momentum.color[1:], label_text(edge.momentum.label), coordinate(label)))
    for item in document.annotations:
        if isinstance(item, FreeLabel):
            if item.text:
                lines.append("  \\fmfiv{l={\\color[HTML]{%s}$%s$},l.a=0,l.d=0}{%s}" % (item.color[1:], label_text(item.text), coordinate((item.x, item.y))))
        else:
            ink = foreground(item.color)
            lines.append("  \\fmfi{plain%s}{%s--%s}" % (ink, coordinate((item.x1, item.y1)), coordinate((item.x2, item.y2))))
            dx, dy = item.x2 - item.x1, item.y2 - item.y1
            length = math.hypot(dx, dy) or 1
            lines.append("  \\fmfi{phantom_arrow%s}{%s--%s}" % (ink, coordinate((item.x2 - dx / length * 12, item.y2 - dy / length * 12)), coordinate((item.x2, item.y2))))
    for vertex in document.vertices:
        if vertex.label:
            lines.append("  \\fmfiv{l={$%s$},l.a=0,l.d=0}{(%.6fw,%.6fh)}" % (label_text(vertex.label), (vertex.x + vertex.labelX) / WIDTH, 1 - (vertex.y + vertex.labelY) / HEIGHT))
    lines.extend(("\\end{%s}" % graph, "\\end{fmffile}", "\\endgroup"))
    return "\n".join(lines)


def _pst(document: Diagram) -> str:
    colors = _colors(document)
    lines = [
        "% Generated by Feynman Diagram Studio",
        "% Requires \\usepackage{pst-feyn}, \\usepackage{pstricks-add}, and \\usepackage{xcolor}",
        "% For direct PDF output, load auto-pst-pdf and enable shell escape.",
        "\\begingroup",
        _font_command(document),
        "\\psset{unit=%.6fmm}" % (document.style.widthMm / WIDTH),
        "\\begin{pspicture}(0,0)(720,480)",
    ]
    lines[5:5] = ["\\definecolor{%s}{HTML}{%s}" % (name, color[1:]) for color, name in colors.items()]
    vertices = {item.id: item for item in document.vertices}
    for edge in document.edges:
        start, end = vertices.get(edge.from_), vertices.get(edge.to)
        if start is None or end is None:
            continue
        for offset in bundle_offsets(edge):
            points, _ = connected_geometry(document, edge, offset)
            sampled = points[:: max(1, len(points) // 80)]
            if sampled[-1] != points[-1]:
                sampled.append(points[-1])
            coords = "".join("(%s,%s)" % (_n(x), _n(HEIGHT - y)) for x, y in sampled)
            style = ",linestyle=dashed" if edge.kind in ("scalar", "ghost") else ""
            lines.append("  \\psline[linecolor=%s,linewidth=%spt%s]%s" % (colors[edge.color.upper()], _n(document.style.strokePt), style, coords))
        if edge.arrow != "none":
            _, middle = geometry(start, end, edge)
            direction = 1 if edge.arrow == "forward" else -1
            dx, dy = middle.tx * 12 * direction, middle.ty * 12 * direction
            lines.append("  \\psline[linecolor=%s,linewidth=%spt]{->}(%s,%s)(%s,%s)" % (colors[edge.color.upper()], _n(document.style.strokePt), _n(middle.x - dx), _n(HEIGHT - middle.y + dy), _n(middle.x + dx), _n(HEIGHT - middle.y - dy)))
        if edge.label:
            _, middle = geometry(start, end, edge)
            x, y = edge_label_position(middle, edge)
            lines.append("  \\rput(%s,%s){\\color{%s}$%s$}" % (_n(x), _n(HEIGHT - y), colors[edge.color.upper()], edge.label))
        if edge.momentum:
            points, arrow, label = momentum_geometry(start, end, edge)
            ink = colors[edge.momentum.color.upper()]
            sampled = points[::max(1, len(points) // 80)]
            if sampled[-1] != points[-1]:
                sampled.append(points[-1])
            coords = "".join("(%s,%s)" % (_n(x), _n(HEIGHT - y)) for x, y in sampled)
            lines.append("  \\psline[linecolor=%s,linewidth=%spt]%s" % (ink, _n(document.style.strokePt * 0.8), coords))
            tip = arrow[0]
            base = ((arrow[1][0] + arrow[2][0]) / 2, (arrow[1][1] + arrow[2][1]) / 2)
            lines.append("  \\psline[linecolor=%s,linewidth=%spt]{->}(%s,%s)(%s,%s)" % (ink, _n(document.style.strokePt * 0.8), _n(base[0]), _n(HEIGHT - base[1]), _n(tip[0]), _n(HEIGHT - tip[1])))
            if edge.momentum.label:
                lines.append("  \\rput(%s,%s){\\color{%s}$%s$}" % (_n(label[0]), _n(HEIGHT - label[1]), ink, edge.momentum.label))
    for item in document.annotations:
        ink = colors[item.color.upper()]
        if isinstance(item, FreeLabel):
            if item.text:
                lines.append("  \\rput(%s,%s){\\color{%s}$%s$}" % (_n(item.x), _n(HEIGHT - item.y), ink, item.text))
        else:
            lines.append("  \\psline[linecolor=%s,linewidth=%spt]{->}(%s,%s)(%s,%s)" % (ink, _n(document.style.strokePt), _n(item.x1), _n(HEIGHT - item.y1), _n(item.x2), _n(HEIGHT - item.y2)))
    for vertex in document.vertices:
        marker = vertex.marker if vertex.marker else ("dot" if vertex.visible else "none")
        if marker != "none":
            radius = 2 if marker == "dot" else vertex.markerSize
            if marker in ("dot", "filled"):
                fill = "fillstyle=solid,fillcolor=fdscolor0"
            elif marker == "open":
                fill = "fillstyle=solid,fillcolor=white"
            else:
                pattern = {"hatched": "hlines*", "crosshatched": "crosshatch*", "dotted": "dots*"}[marker]
                fill = "fillstyle=%s,fillcolor=white,hatchcolor=fdscolor0" % pattern
            lines.append("  \\pscircle[linecolor=fdscolor0,%s](%s,%s){%s}" % (fill, _n(vertex.x), _n(HEIGHT - vertex.y), _n(radius)))
        if vertex.label:
            lines.append("  \\rput(%s,%s){$%s$}" % (_n(vertex.x + vertex.labelX), _n(HEIGHT - vertex.y - vertex.labelY), vertex.label))
    lines.append("\\end{pspicture}")
    lines.append("\\endgroup")
    return "\n".join(lines)


def _dash_segments(points: List[Tuple[float, float]], on: float, off: float) -> Iterable[Tuple[Tuple[float, float], Tuple[float, float]]]:
    distance = 0.0
    period = on + off
    for a, b in zip(points, points[1:]):
        length = math.hypot(b[0] - a[0], b[1] - a[1])
        if not length:
            continue
        consumed = 0.0
        while consumed < length - 1e-6:
            phase = (distance + consumed) % period
            step = min(length - consumed, max(1e-6, (on if phase < on else period) - phase))
            if phase < on:
                start = tuple(a[index] + (b[index] - a[index]) * consumed / length for index in (0, 1))
                end = tuple(a[index] + (b[index] - a[index]) * (consumed + step) / length for index in (0, 1))
                yield start, end
            consumed += step
        distance += length


def _axo(document: Diagram) -> str:
    scale = document.style.widthMm * 72.27 / (25.4 * WIDTH)
    def pt(value: float) -> str:
        return _n(value * scale)

    lines = [
        "% Generated by Feynman Diagram Studio",
        "% Requires \\usepackage{axodraw2} and \\usepackage{xcolor} (run axohelp for direct PDF).",
        "\\begingroup",
        _font_command(document),
        "\\SetWidth{%s}" % _n(document.style.strokePt),
        "\\begin{axopicture}(%s,%s)" % (pt(WIDTH), pt(HEIGHT)),
    ]
    vertices = {item.id: item for item in document.vertices}
    for edge in document.edges:
        start, end = vertices.get(edge.from_), vertices.get(edge.to)
        if start is None or end is None:
            continue
        for offset in bundle_offsets(edge):
            points, middle = connected_geometry(document, edge, offset)
            sampled = points[:: max(1, len(points) // 100)]
            if sampled[-1] != points[-1]:
                sampled.append(points[-1])
            segments = _dash_segments(sampled, 9 if edge.kind == "scalar" else 1, 7) if edge.kind in ("scalar", "ghost") else zip(sampled, sampled[1:])
            for a, b in segments:
                lines.append("  {\\color[HTML]{%s}\\Line(%s,%s)(%s,%s)}" % (edge.color[1:], pt(a[0]), pt(HEIGHT - a[1]), pt(b[0]), pt(HEIGHT - b[1])))
            if edge.arrow != "none":
                direction = 1 if edge.arrow == "forward" else -1
                dx, dy = middle.tx * 12 * direction, middle.ty * 12 * direction
                lines.append("  {\\color[HTML]{%s}\\ArrowLine(%s,%s)(%s,%s)}" % (edge.color[1:], pt(middle.x - dx), pt(HEIGHT - middle.y + dy), pt(middle.x + dx), pt(HEIGHT - middle.y - dy)))
        if edge.label:
            _, middle = geometry(start, end, edge)
            x, y = edge_label_position(middle, edge)
            lines.append("  {\\color[HTML]{%s}\\Text(%s,%s)[c]{$%s$}}" % (edge.color[1:], pt(x), pt(HEIGHT - y), edge.label))
        if edge.momentum:
            points, arrow, label = momentum_geometry(start, end, edge)
            sampled = points[::max(1, len(points) // 100)]
            if sampled[-1] != points[-1]:
                sampled.append(points[-1])
            ink = edge.momentum.color[1:]
            for a, b in zip(sampled, sampled[1:]):
                lines.append("  {\\color[HTML]{%s}\\Line(%s,%s)(%s,%s)}" % (ink, pt(a[0]), pt(HEIGHT - a[1]), pt(b[0]), pt(HEIGHT - b[1])))
            tip = arrow[0]
            base = ((arrow[1][0] + arrow[2][0]) / 2, (arrow[1][1] + arrow[2][1]) / 2)
            lines.append("  {\\color[HTML]{%s}\\ArrowLine(%s,%s)(%s,%s)}" % (ink, pt(base[0]), pt(HEIGHT - base[1]), pt(tip[0]), pt(HEIGHT - tip[1])))
            if edge.momentum.label:
                lines.append("  {\\color[HTML]{%s}\\Text(%s,%s)[c]{$%s$}}" % (ink, pt(label[0]), pt(HEIGHT - label[1]), edge.momentum.label))
    for item in document.annotations:
        ink = item.color[1:]
        if isinstance(item, FreeLabel):
            if item.text:
                lines.append("  {\\color[HTML]{%s}\\Text(%s,%s)[c]{$%s$}}" % (ink, pt(item.x), pt(HEIGHT - item.y), item.text))
        else:
            lines.append("  {\\color[HTML]{%s}\\ArrowLine(%s,%s)(%s,%s)}" % (ink, pt(item.x1), pt(HEIGHT - item.y1), pt(item.x2), pt(HEIGHT - item.y2)))
    for vertex in document.vertices:
        marker = vertex.marker if vertex.marker else ("dot" if vertex.visible else "none")
        if marker != "none":
            radius = 2 if marker == "dot" else vertex.markerSize
            if marker in ("dot", "filled"):
                lines.append("  \\Vertex(%s,%s){%s}" % (pt(vertex.x), pt(HEIGHT - vertex.y), pt(radius)))
            else:
                lines.append("  {\\color{white}\\Vertex(%s,%s){%s}}" % (pt(vertex.x), pt(HEIGHT - vertex.y), pt(radius)))
                lines.append("  \\ECirc(%s,%s){%s}" % (pt(vertex.x), pt(HEIGHT - vertex.y), pt(radius)))
                if marker in ("hatched", "crosshatched"):
                    for angle in ((45, -45) if marker == "crosshatched" else (45,)):
                        direction = (math.cos(math.radians(angle)), math.sin(math.radians(angle)))
                        normal = (-direction[1], direction[0])
                        offset = -radius + 4
                        while offset <= radius - 4:
                            half = math.sqrt(radius * radius - offset * offset)
                            a = (vertex.x + normal[0] * offset - direction[0] * half, vertex.y + normal[1] * offset - direction[1] * half)
                            b = (vertex.x + normal[0] * offset + direction[0] * half, vertex.y + normal[1] * offset + direction[1] * half)
                            lines.append("  \\Line(%s,%s)(%s,%s)" % (pt(a[0]), pt(HEIGHT - a[1]), pt(b[0]), pt(HEIGHT - b[1])))
                            offset += 7
                elif marker == "dotted":
                    x = -radius + 4
                    while x <= radius - 4:
                        y = -radius + 4
                        while y <= radius - 4:
                            if x * x + y * y <= (radius - 3) ** 2:
                                lines.append("  \\Vertex(%s,%s){%s}" % (pt(vertex.x + x), pt(HEIGHT - vertex.y - y), pt(1.35)))
                            y += 7
                        x += 7
        if vertex.label:
            lines.append("  \\Text(%s,%s)[c]{$%s$}" % (pt(vertex.x + vertex.labelX), pt(HEIGHT - vertex.y - vertex.labelY), vertex.label))
    lines.extend(("\\end{axopicture}", "\\endgroup"))
    return "\n".join(line.strip() + "%" if line.startswith("  ") else line for line in lines)


def latex_source(document: Diagram, format_name: str) -> str:
    reasons = unsupported_features(document, format_name)
    if reasons:
        raise ValueError("{} cannot export this diagram: {}.".format(format_name, "; ".join(reasons)))
    if format_name == "tikz-feynman":
        return _tikz(document, "tikz-feynman")
    if format_name == "tikz-feynhand":
        return _tikz(document, "tikz-feynhand")
    if format_name in ("feynmp", "feynmf"):
        return _fmf(document, format_name)
    if format_name == "pst-feyn":
        return _pst(document)
    if format_name == "axodraw2":
        return _axo(document)
    raise ValueError("Unsupported LaTeX format: {}".format(format_name))


def standalone_source(document: Diagram, format_name: str) -> str:
    option = next((item for item in FORMATS if item.value == format_name), None)
    if option is None:
        raise ValueError("Unsupported LaTeX format: {}".format(format_name))
    packages: Dict[str, Iterable[str]] = {
        "tikz-feynman": (r"\usepackage[compat=1.1.0]{tikz-feynman}", r"\usetikzlibrary{arrows.meta,patterns,decorations.markings}"),
        "tikz-feynhand": (r"\usepackage{tikz-feynhand}", r"\usetikzlibrary{arrows.meta,patterns,decorations.markings}"),
        "feynmp": (r"\usepackage{feynmp}", r"\DeclareGraphicsRule{.1}{mps}{*}{}"),
        "feynmf": (r"\usepackage{feynmf}",),
        "pst-feyn": (r"\usepackage{auto-pst-pdf}", r"\usepackage{pst-feyn}", r"\usepackage{pstricks-add}"),
        "axodraw2": (r"\usepackage{axodraw2}",),
    }
    preamble = [r"\documentclass{article}", "% Compiler: " + option.compiler, r"\usepackage{xcolor}"]
    preamble.extend(packages[format_name])
    preamble.extend((r"\pagestyle{empty}", r"\begin{document}", r"\centering", latex_source(document, format_name), r"\end{document}"))
    return "\n".join(preamble)
